# Generated by Django 4.2.21 on 2025-09-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
